name: Build and Push Docker image

on:
  release:
    types: [published]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 #v3.10.0

      - name: Set up SSH key
        uses: shimataro/ssh-key-action@d4fffb50872869abe2d9a9098a6d9c5aa7d16be4 # v2.7.0
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.SSH_HOST }}

      - name: Set up Git
        run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/

      - name: Login to Google Cloud
        uses: google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935 # v2.1.8
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@77e7a554d41e2ee56fc945c52dfd3f33d12def9a  # v2.1.4

      - name: Configure Google Cloud Docker registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and push backend Docker image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          push: true
          tags: europe-west1-docker.pkg.dev/openfort/dockers/sample-ecosystem-backend:${{ github.event.release.tag_name }}
          file: ./wallet-ui/backend/Dockerfile
          context: ./wallet-ui/backend
          build-args: |
            "SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          push: true
          tags: europe-west1-docker.pkg.dev/openfort/dockers/sample-ecosystem-frontend:${{ github.event.release.tag_name }}
          file: ./wallet-ui/frontend/Dockerfile
          context: ./wallet-ui/frontend
          build-args: |
            "SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}"
            "REACT_APP_APP_NAME=${{ vars.REACT_APP_APP_NAME }}"
            "REACT_APP_OPENFORT_PUBLIC_KEY=${{ vars.REACT_APP_OPENFORT_PUBLIC_KEY }}"
            "REACT_APP_SHIELD_PUBLIC_KEY=${{ vars.REACT_APP_SHIELD_PUBLIC_KEY }}"
            "REACT_APP_BACKEND_URL=${{ vars.REACT_APP_BACKEND_URL }}"
            "REACT_APP_OPENFORT_ECOSYSTEM_ID=${{ vars.REACT_APP_OPENFORT_ECOSYSTEM_ID }}"

      - name: Build and push sdk Docker image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          push: true
          tags: europe-west1-docker.pkg.dev/openfort/dockers/sample-ecosystem-sdk:${{ github.event.release.tag_name }}
          file: ./usage-examples/wagmi-nextjs/Dockerfile
          context: ./usage-examples/wagmi-nextjs
          build-args: |
            "SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}"
            "NEXT_PUBLIC_POLICY_ID=${{ secrets.NEXT_PUBLIC_POLICY_ID }}"

      - name: Clone Infra Repository
        run: |
          git clone git@github.com:openfort-xyz/kube.git

      - name: Update frontend version
        uses: mikefarah/yq@8bf425b4d1344db7cd469a8d10a390876e0c77fd # v4.45.1
        with:
          cmd: yq -i '.sample_ecosystem_frontend.tag = "${{ github.event.release.tag_name }}"' kube/values.yaml

      - name: Update backend version
        uses: mikefarah/yq@8bf425b4d1344db7cd469a8d10a390876e0c77fd # v4.45.1
        with:
          cmd: yq -i '.sample_ecosystem_backend.tag = "${{ github.event.release.tag_name }}"' kube/values.yaml

      - name: Update SDK sample version
        uses: mikefarah/yq@8bf425b4d1344db7cd469a8d10a390876e0c77fd # v4.45.1
        with:
          cmd: yq -i '.sample_ecosystem_sdk.tag = "${{ github.event.release.tag_name }}"' kube/values.yaml

      - name: Update Infra Repository
        run: |
          cd kube
          git config --global user.email "cd@openfort.xyz"
          git config --global user.name "CD"
          git add .
          git commit -m "Update ecosystem sample version to ${{ github.event.release.tag_name }}"
          git push

      - name: Logout of Docker CLI
        run: docker logout europe-west1-docker.pkg.dev
